/**
 * Generate a Zed theme extension from the VS Code themes produced by
 * `yarn out`. Writes into `zed-extension/`, which can be imported into
 * Zed via Extensions -> "Install Dev Extension".
 *
 *   yarn out          # regenerate VS Code themes + Zed extension
 *   yarn out:zed      # regenerate only the Zed extension
 */
const fs = require('fs-extra')
const path = require('node:path')

const { convertTheme } = require('./lib/vscode-to-zed')
const { readJson } = require('./lib/read-json')

const BASE = path.resolve(__dirname, '..')
const THEMES_DIR = path.join(BASE, 'themes')
// Light themes are built into the sibling repo by `yarn out:light`.
// Override with LIGHT_THEMES_DIR when the repo lives elsewhere.
const LIGHT_THEMES_DIR =
  process.env.LIGHT_THEMES_DIR || path.resolve(__dirname, '../../niketa-theme/themes')
const EXTENSION_DIR = path.join(BASE, 'zed-extension')
const EXTENSION_THEMES_DIR = path.join(EXTENSION_DIR, 'themes')

const packageJson = readJson('package.json')
const author = packageJson.publisher || (Array.isArray(packageJson.authors) ? packageJson.authors[0] : '')
const extensionId = packageJson.zedExtensionId || 'niketa-dark'

function readLightFamilyName() {
  try {
    const lightPackage = readJson('package.json', path.resolve(__dirname, '../../niketa-theme'))
    return lightPackage.displayName || 'Niketa Light'
  } catch {
    return 'Niketa Light'
  }
}

function generateExtensionManifest() {
  return [
    `id = "${extensionId}"`,
    `name = "${packageJson.displayName || 'Niketa Dark'}"`,
    'schema_version = 1',
    `version = "${packageJson.version}"`,
    `authors = ["${author}"]`,
    `description = "${(packageJson.description || '').replace(/"/g, '\\"')}"`,
    `repository = "${packageJson.repository.url}"`,
    '',
  ].join('\n')
}

function toKebabCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
}

function main() {
  const sources = [
    { dir: THEMES_DIR, familyName: packageJson.displayName || 'Niketa Theme' },
    { dir: LIGHT_THEMES_DIR, familyName: readLightFamilyName() },
  ]

  fs.ensureDirSync(EXTENSION_THEMES_DIR)
  const themeNames = new Set()
  let totalUnmatched = {}
  let converted = 0

  for (const source of sources) {
    if (!fs.existsSync(source.dir)) {
      console.log(`  skip ${source.dir} (not found)`)
      continue
    }
    const files = fs.readdirSync(source.dir).filter(file => file.endsWith('.json'))
    if (files.length === 0) {
      console.log(`  skip ${source.dir} (no themes)`)
      continue
    }

    for (const file of files) {
      const vscodeTheme = fs.readJsonSync(path.join(source.dir, file))
      const { theme, unmatched } = convertTheme(vscodeTheme, {
        familyName: source.familyName,
        author,
      })

      const themeName = themeNames.has(theme.themes[0].name)
        ? `${source.familyName} ${theme.themes[0].name}`
        : theme.themes[0].name
      themeNames.add(themeName)
      theme.themes[0].name = themeName

      if (unmatched.length > 0) {
        for (const scope of unmatched) {
          totalUnmatched[scope] = (totalUnmatched[scope] || 0) + 1
        }
      }

      const outputFile = path.join(EXTENSION_THEMES_DIR, `${toKebabCase(themeName)}.json`)
      fs.outputJsonSync(outputFile, theme, { spaces: 2 })
      converted += 1
      console.log(`  wrote ${path.relative(BASE, outputFile)}`)
    }
  }

  fs.outputFileSync(path.join(EXTENSION_DIR, 'extension.toml'), generateExtensionManifest())
  fs.outputFileSync(path.join(EXTENSION_DIR, 'README.md'), generateReadme())

  const unmappedCount = Object.keys(totalUnmatched).length
  console.log(`\nWrote ${converted} themes to zed-extension/`)
  console.log(`Unmapped scopes: ${unmappedCount}`)
  if (unmappedCount > 0) {
    const sample = Object.entries(totalUnmatched)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20)
    for (const [scope, count] of sample) {
      console.log(`  ${count}x  ${scope}`)
    }
  }
}

function generateReadme() {
  const count = String(
    fs.readdirSync(THEMES_DIR).filter(file => file.endsWith('.json')).length +
      (fs.existsSync(LIGHT_THEMES_DIR)
        ? fs.readdirSync(LIGHT_THEMES_DIR).filter(file => file.endsWith('.json')).length
        : 0)
  )
  return `<!-- This file is generated by \`yarn out:zed\`. -->
# ${packageJson.displayName || 'Niketa Theme'} (Zed)

Zed extension generated from ${count} themes (dark + light).

## Install as dev extension

1. Run \`yarn out\` (or \`yarn out:zed\`) to regenerate the extension.
2. In Zed open the Extensions panel (\`zed: extensions\`).
3. Click **Install Dev Extension** (or run \`zed: install dev extension\`).
4. Select this \`zed-extension/\` directory.
5. Pick the theme via \`theme selector: toggle\` (\`cmd-k cmd-t\`).
`
}

main()